# Generated by Django 4.0.5 on 2022-06-23 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0007_alter_sensorerror_error_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='id_error_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_error', to='atlas.sensorerror', verbose_name='Журнал ошибки'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='id_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sensor', to='atlas.sensor', verbose_name='Датчик'),
        ),
        migrations.AlterField(
            model_name='useraccessgroups',
            name='companys',
            field=models.ManyToManyField(null=True, to='atlas.company'),
        ),
        migrations.AlterField(
            model_name='useraccessgroups',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
